switch("nomain")
switch("compileOnly")
switch("nimcache", "nimcache")
switch("gc", "arc")
switch("cpu", "arm")
switch("os", "freertos")
switch("define", "useMalloc")
switch("define", "noSignalHandler")
switch("threads", "on")
switch("tlsEmulation", "off")
switch("lineDir", "off")
switch("lineTrace", "off")
switch("stackTrace", "off")
